### PR TITLE
3d and 4th challenges

### PR DESCRIPTION
**Pull request by nfadeeva**

### CODE REVIEW

**Comment by lizaku** [comment]
@nfadeeva What does check_state() do? I don't get

**Comment by nfadeeva** [comment]
@lizaku it check if the end or start state doesn't satisfy constraints and if not it raises and error, this method should be private, I'll fix it

**Comment by lizaku** [comment]
So constraints cannot be just an empty dictionary? Because then this method would raise an error too.

**Comment by aliskin** [comment]
please also rename it to something like check_state_validity

**Comment by nfadeeva** [comment]
@lizaku yes, and maybe we need to check it in __init__, I added this check but don't like the way I do it, maybe you will rewrite it in more elegant way

**Comment by nfadeeva** [comment]
@lizaku @aliskin @EmaPajic please review changes and add your fixes into code if it needs

**Comment by aliskin** [comment]
I don't think that we should unite all our solutions in a one big class because:
1. the main problem (and the 2nd challenge) uses different data structures than 3d and 4th challenge: the former uses only two lists and the latter uses graph to represent the whole set of all possible parking states.
2. current code does not pass existing tests because each time it builds a graph that has a size of 100000! vertices for a parking of length 100000. We definitely should not try to make it run at that moment because the deadline is too soon.

**Comment by nfadeeva** [comment]
But if we have two different data structures for our assignment we need to make the input validation for both structures and that’s why I think that we need to unite them into one big

**Comment by nfadeeva** [comment]
And I don’t think that it is a problem that it creates a graph every time, we can build a graph in different function so it would not build every time

**Comment by nfadeeva** [comment]
But if  you want you can undo integration

**Pull request closed without merging**
